Repository ucsb-cs156-s25/proj-rec-s25-16, pull requests merged in 2025-05, with the labels that each got.

#26 jl changed the default status of users to student = true
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
Labels: 5

#27 dk - added recommendation request table to pending requests page
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/stories/pages/Requests/PendingRequestsPage.stories.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
Labels: 10, Merge Candidate-CI

#29 Dk - Professors can update status column on pending requests page
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/main/utils/RecommendationRequestUtils.js
  frontend/src/stories/pages/Requests/PendingRequestsPage.stories.js
  frontend/src/tests/pages/Requests/CompletedRequestsPage.test.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
Labels: 10, Merge Candidate-CI

#33 dk/cl - date completed stored in backend and displayed on table
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10

#38 Dk - fixed delete button functionality
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/utils/RecommendationRequestUtils.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
Labels: 10

#36 cl - changing home page message and brand
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 5, Merge Candidate-CI

#28 Jl user role
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: 5

#41 Jl remove student everywhere
  src/main/java/edu/ucsb/cs156/rec/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorTests.java
  src/test/java/edu/ucsb/cs156/rec/web/HomePageWebIT.java
Labels: 10

#39 cl - all rec endpoints for admin
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI

#47 Cl rec admin page
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminRequestsPage.js
  frontend/src/tests/pages/AdminRequestsPage.test.js
Labels: 10, Merge Candidate-CI

#37 sp - Create RequestTypeForm for Admins and Professors with Storybook and Test
  frontend/src/main/components/RequestType/RequestTypeForm.js
  frontend/src/stories/components/RequestType/RequestTypeForm.stories.js
  frontend/src/tests/components/RequestType/RequestTypeForm.test.js
Labels: 10
