Repository ucsb-cs156-s25/proj-rec-s25-16, pull requests merged in 2025-06, with the labels that each got.

#50 jh - Fix changelog master .json file
  src/main/resources/db/migration/changelog-master.json
  src/main/resources/db/migration/changes/RequestType.json
Labels: bug, 0, Ready-For-Staff, Merge Candidate-CI

#52 jl - bug fix, removed extra role_student from the codebase
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorTests.java
Labels: bug, Ready-For-Staff, Merge Candidate-CI

#40 sp - feat: Add placeholder pages for RequestType Index, Create, and Edit
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/RequestType/RequestTypesCreatePage.js
  frontend/src/main/pages/RequestType/RequestTypesEditPage.js
  frontend/src/main/pages/RequestType/RequestTypesIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/RequestType/RequestTypesCreatePage.test.js
  frontend/src/tests/pages/RequestType/RequestTypesEditPage.test.js
  frontend/src/tests/pages/RequestType/RequestTypesIndexPage.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: Ready-For-Staff
